----------------------------------------------
--PROJECT: MELD-B 1377
--WP02 (Work Package 02) - Stage 01 
--AUTHOR: roberta.chiovoloni@swansea.ac.uk
----------------------------------------------
--AIM: Create Cohort linkage table, i.e. tables where each row is an individual in the cohort and each column flags if that individual has records in one specific datasource. 

-- Steps: 1- Use the SMC cohort table to create list of ALF_PE -> COHORT_LINKAGE_TABLE
--		  2- For each health dataset create a temporary table (e.g. ADDE_T) containing only the ALF_PE 
--			 common to this datasets and the cohort and (where needed) the date of the event recorded for each ALF_PE
--	      3- Add a column to COHORT_LINKAGE_TABLE for each health dataset. 
--			 The value of this column is 1 if the ALF_PE is in the health datasource temporary table (i.e. if he has record in that health datasource) 
--			 and the recorded event > 2000-01-01
----------------------------------------------
--Final Table created: 
--	 WP02_COHORT_LINKAGE_TABLE 

--DROP TABLES TO RUN THE CODE
--Final table created: 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_COHORT_LINKAGE_TABLE');

--Temporary Table created: 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WDSD_AP2_T');
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.TEMP_WP02_COHORT_TABLE');

CALL FNC.DROP_IF_EXISTS ('SAILW1377V.ADDE_T');
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.ADBE_T');

CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WLGP_GP_REG_T'); 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WLGP_EVENTS_T');
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WDSD_LSOA_T');

CALL FNC.DROP_IF_EXISTS ('SAILW1377V.PEDW_ADM_T'); 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.PEDW_DIAG_T');
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.PEDW_OPER_T');

CALL FNC.DROP_IF_EXISTS ('SAILW1377V.EDDS_T'); 

CALL FNC.DROP_IF_EXISTS ('SAILW1377V.OPDW_OUT_T'); 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.OPDW_OUT_DIAG_T'); 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.OPDW_OUT_OPER_T'); 

CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WRRS_T');
---------------------------------------
--Variables 

CREATE OR REPLACE VARIABLE SAILW1377V.COHORT_ST_DT DATE DEFAULT '2000-01-01'; 
CREATE OR REPLACE VARIABLE SAILW1377V.COHORT_END_DT DATE DEFAULT '2022-12-31';
CREATE OR REPLACE VARIABLE SAILW1377V.AGE_MAX INTEGER DEFAULT 38325; --105 years of age 

----------------------------------------------
--Create table containing all the ALF_PE of individuals in the SMC cohort 
CREATE TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE (
	ALF_PE BIGINT
	)
DISTRIBUTE BY HASH(ALF_PE); 
--
INSERT INTO SAILW1377V.WP02_COHORT_LINKAGE_TABLE (
	SELECT DISTINCT 
		ALF_PE 
	FROM 
		SAILW1377V.WP02_COHORT_TABLE
); 

SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_COHORT_LINKAGE_TABLE wclt ; 
----------------------------------------------------------------
--ADDE AND ADBE
----------------------------------------------------------------
--Add flag columns, and set them to 0 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_ADDE SMALLINT NOT NULL DEFAULT 0; 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_ADBE SMALLINT NOT NULL DEFAULT 0;
--
CREATE TABLE SAILW1377V.ADDE_T (
	ALF_PE BIGINT, 
	DOD DATE
); 
--
CREATE TABLE SAILW1377V.ADBE_T (
	ALF_PE BIGINT, 
	WOB DATE
); 

INSERT INTO SAILW1377V.ADDE_T (  --includes only individuals who died before cohort_end_date 
	SELECT DISTINCT 
		A.ALF_PE, DOD 
	FROM 
		SAILW1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.ADDE_DEATHS_20230601 B
	ON 
		A.ALF_PE = B.ALF_PE
	WHERE 
		a.DOD <= SAILW1377V.COHORT_END_DT
	); 
--
--
INSERT INTO SAILW1377V.ADBE_T (
	SELECT DISTINCT 
		A.ALF_PE, B.WOB 
	FROM 
		SAILw1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.ADBE_BIRTHS_20230401 B
	ON 
		A.ALF_PE = B.ALF_PE
	WHERE 
		A.WOB <= SAILW1377V.COHORT_END_DT --not including anyone who is born after COHORT_END_DT
	); 
--

--updating cohort_linkage table 
UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_ADDE = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.ADDE_T); 
--
UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_ADBE = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.ADBE_T); 
--
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.ADDE_T'); 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.ADBE_T');
--
--------------------------------------------------------------------------------
--WLGP/ WDSD / WLGP_EVENT
--------------------------------------------------------------------------------
--Add flag columns, and set them to 0 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_WLGP_GP_REG SMALLINT NOT NULL DEFAULT 0; 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_WLGP_GP_EVENTS SMALLINT NOT NULL DEFAULT 0; 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_WDSD_LSOA SMALLINT NOT NULL DEFAULT 0;
--
--Creating temp tables including only ALF_PE in teh SMC cohort 
CREATE TABLE SAILW1377V.WLGP_GP_REG_T (
	ALF_PE BIGINT
);
--
INSERT INTO SAILW1377V.WLGP_GP_REG_T (
	SELECT DISTINCT 
		A.ALF_PE 
	FROM 	
		SAILW1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.WLGP_CLEAN_GP_REG_BY_PRAC_INCLNONSAIL_MEDIAN_20230401 B
	ON 
		A.ALF_PE = B.ALF_PE
	WHERE 
		B.START_DATE <= SAILW1377V.COHORT_END_DT  --including only individuals with data before cohort_end_dt 
	); 
--
CREATE TABLE sailw1377v.WLGP_EVENTS_T (
	ALF_PE BIGINT
	); 

INSERT INTO SAILW1377V.WLGP_EVENTS_T (
	SELECT DISTINCT 
		A.ALF_PE 
	FROM 
		SAILW1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.WLGP_GP_EVENT_CLEANSED_20230401 B
	ON 
		A.ALF_PE = B.ALF_PE
	WHERE 
		B.EVENT_DT >= '1990-01-01' AND B.EVENT_DT <= SAILW1377V.COHORT_END_DT --we want data from 1990
	); 
--
CREATE TABLE SAILW1377V.WDSD_LSOA_T(
	ALF_PE BIGINT
	); 

INSERT INTO SAILW1377V.WDSD_LSOA_T (
	SELECT DISTINCT 
		B.ALF_PE 
	FROM 
		SAILW1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.WDSD_SINGLE_CLEAN_GEO_CHAR_LSOA2011_20230605 B
	ON 
		A.ALF_PE = B.ALF_PE
	WHERE
		B.START_DATE <= SAILW1377V.COHORT_END_DT
); 
--
--Updating cohort_linkage table 
UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_WLGP_GP_REG = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.WLGP_GP_REG_T); 

UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_WLGP_GP_EVENTS = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.WLGP_EVENTS_T); 

UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_WDSD_LSOA = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.WDSD_LSOA_T);
--
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WLGP_GP_REG_T'); 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WLGP_EVENTS_T');
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WDSD_LSOA_T');
--

--------------------------------------------------------
--PEDW 
--------------------------------------------------------
--Add flag columns, and set them to 0 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_PEDW_ADM SMALLINT NOT NULL DEFAULT 0; 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_PEDW_DIAG SMALLINT NOT NULL DEFAULT 0; 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_PEDW_OPER SMALLINT NOT NULL DEFAULT 0;

--Creating temp tables including only ALF_PE in teh SMC cohort 
CREATE TABLE SAILW1377V.PEDW_ADM_T (
ALF_PE BIGINT
); 

INSERT INTO SAILW1377V.PEDW_ADM_T (
	SELECT DISTINCT 
		A.ALF_PE 
	FROM 
		SAILW1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.PEDW_ADMISSIONS_20230605 B
	ON 
		A.ALF_PE = B.ALF_PE
	WHERE 
		START_DATE >='1990-01-01' AND START_DATE <= SAILW1377V.COHORT_END_DT
	); 
--
CREATE TABLE SAILW1377V.PEDW_DIAG_T (
	ALF_PE BIGINT
	); 

INSERT INTO SAILW1377V.PEDW_DIAG_T (
	SELECT DISTINCT 
		B.ALF_PE 
	FROM 
		SAILW1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.PEDW_SINGLE_DIAG_20230605 B
	ON 
		A.ALF_PE = B.ALF_PE 
	WHERE 
		START_DATE >= '1990-01-01' AND START_DATE <= SAILW1377V.COHORT_END_DT
	); 
--
CREATE TABLE SAILW1377V.PEDW_OPER_T(
	ALF_PE BIGINT
	); 

INSERT INTO SAILW1377V.PEDW_OPER_T (
	SELECT DISTINCT 
		B.ALF_PE 
	FROM 
		SAILW1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.PEDW_SINGLE_OPER_20230605 B
	ON 
		A.ALF_PE = B.ALF_PE
	WHERE 
		START_DATE >= '1990-01-01' AND START_DATE <= SAILW1377V.COHORT_END_DT
	); 
--

--Updating cohort_linkage table 
UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_PEDW_ADM = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.PEDW_ADM_T); 

UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_PEDW_DIAG = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.PEDW_DIAG_T ); 

UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_PEDW_OPER = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.PEDW_OPER_T ); 

--
--

CALL FNC.DROP_IF_EXISTS ('SAILW1377V.PEDW_ADM_T'); 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.PEDW_DIAG_T');
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.PEDW_OPER_T');
--
--------------------------------------------------------
--EDDS 
--------------------------------------------------------
--Add flag columns, and set them to 0 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_EDDS SMALLINT NOT NULL DEFAULT 0; 
--
CREATE TABLE SAILW1377V.EDDS_T (
	ALF_PE BIGINT,
	HEDT DATE
); 

INSERT INTO SAILW1377V.EDDS_T (
	SELECT DISTINCT 
		A.ALF_PE, HEALTH_EVENT_DT 
	FROM 
		SAILW1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.EDDS_EDDS_20230601 B
	ON 
		A.ALF_PE = B.ALF_PE
	WHERE 
		HEALTH_EVENT_DT >= '1990-01-01' AND HEALTH_EVENT_DT <= SAILW1377V.COHORT_END_DT
	); 
--
UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_EDDS = 1 
WHERE ALF_PE IN 
	(SELECT DISTINCT ALF_PE FROM SAILW1377V.EDDS_T ); 
--
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.EDDS_T'); 
--
--------------------------------------------------------
--OPDW 
--------------------------------------------------------
---Add flag columns, and set them to 0 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_OPDW_OUT SMALLINT NOT NULL DEFAULT 0; 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_OPDW_OUT_DIAG SMALLINT NOT NULL DEFAULT 0; 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_OPDW_OUT_OPER SMALLINT NOT NULL DEFAULT 0; 
--
CREATE TABLE SAILW1377V.OPDW_OUT_T (
	ALF_PE BIGINT, 
	REFDT DATE
); 
--
CREATE TABLE SAILW1377V.OPDW_OUT_DIAG_T (
	ALF_PE BIGINT
); 
--
CREATE TABLE SAILW1377V.OPDW_OUT_OPER_T (
	ALF_PE BIGINT
); 
--
INSERT INTO SAILW1377V.OPDW_OUT_T (
	SELECT DISTINCT 
		A.ALF_PE, B.REF_DT 
	FROM 
		SAILW1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.OPDW_OUTPATIENTS_20230601 B
	ON 
		A.ALF_PE = B.ALF_PE
	WHERE 
		REF_DT >= '1990-01-01' AND REF_DT <= SAILW1377V.COHORT_END_DT
	); 
--
--These other tables need joining since they don't have ALF_PE
INSERT INTO SAILW1377V.OPDW_OUT_DIAG_T (
	SELECT 
		b.alf_pe
	FROM 
		sail1377v.OPDW_OUTPATIENTS_DIAG_20230601 a
	JOIN 
		SAIL1377V.OPDW_OUTPATIENTS_20230601 b
	ON 
		A.PROV_UNIT_CD = B.PROV_UNIT_CD 
		AND A.CASE_REC_NUM_PE = B.CASE_REC_NUM_PE 
		AND A.ATTEND_DT = B.ATTEND_DT 
		AND A.ATT_ID_PE = B.ATT_ID_PE 
	WHERE 
		A.ATTEND_DT >= '1990-01-01' AND A.ATTEND_DT <= SAILW1377V.COHORT_END_DT);
--
INSERT INTO SAILW1377V.OPDW_OUT_OPER_T (
	SELECT 
		B.ALF_PE
	FROM 
		SAIL1377V.OPDW_OUTPATIENTS_OPER_20230601 A
	JOIN 
		SAIL1377V.OPDW_OUTPATIENTS_20230601 B
	ON 
		A.PROV_UNIT_CD = B.PROV_UNIT_CD 
		AND A.CASE_REC_NUM_PE = B.CASE_REC_NUM_PE 
		AND A.ATTEND_DT = B.ATTEND_DT 
		AND A.ATT_ID_PE = B.ATT_ID_PE 
	WHERE 
		A.ATTEND_DT >= '1990-01-01' AND A.ATTEND_DT <= SAILW1377V.COHORT_END_DT);
--
UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_OPDW_OUT = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.OPDW_OUT_T ); 

UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_OPDW_OUT_DIAG = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.OPDW_OUT_DIAG_T ); 

UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_OPDW_OUT_OPER = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.OPDW_OUT_OPER_T ); 
--
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.OPDW_OUT_T'); 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.OPDW_OUT_DIAG_T'); 
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.OPDW_OUT_OPER_T'); 
--
---------------------------------------------------------------
--WRRS (NOTE, HERE I CONSIDER WRRS_REPORT) 
---------------------------------------------------------------
--Add flag columns, and set them to 0 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_WRRS SMALLINT NOT NULL DEFAULT 0; 
--
CREATE TABLE SAILW1377V.WRRS_T (
	ALF_PE BIGINT,
	sdate date
	); 
--
INSERT INTO SAILW1377V.WRRS_T (
	SELECT DISTINCT 
		A.ALF_PE, b.SPCM_COLLECTED_DT FROM SAILW1377V.WP02_COHORT_TABLE A
	JOIN 
		SAIL1377V.WRRS_REPORT_20230705 B
	ON 
		A.ALF_PE = B.ALF_PE
	WHERE 
		SPCM_COLLECTED_DT >= '1990-01-01' AND SPCM_COLLECTED_DT <= SAILW1377V.COHORT_END_DT); 
--
UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_WRRS = 1 
WHERE 
	ALF_PE IN (SELECT DISTINCT ALF_PE FROM SAILW1377V.WRRS_T); 
--
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WRRS_T');
--
---------------------------------------------------------------
--Adding columns for "general" datasource (i.e here we don't distinguish between PEDW_ADM/DIAG etc...)
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_PEDW SMALLINT NOT NULL DEFAULT 0; 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_OPDW SMALLINT NOT NULL DEFAULT 0; 
ALTER TABLE SAILW1377V.WP02_COHORT_LINKAGE_TABLE ADD FLAG_WLGP SMALLINT NOT NULL DEFAULT 0; 

UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_PEDW = 1 
WHERE 
	(FLAG_PEDW_ADM = 1 OR FLAG_PEDW_DIAG = 1 OR FLAG_PEDW_OPER = 1); 
--
UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_OPDW = 1 
WHERE 
	(FLAG_OPDW_OUT = 1 OR FLAG_OPDW_OUT_DIAG = 1 OR FLAG_OPDW_OUT_OPER = 1); 
--
UPDATE SAILW1377V.WP02_COHORT_LINKAGE_TABLE
SET FLAG_WLGP = 1 
WHERE 
	(FLAG_WLGP_GP_REG = 1 OR FLAG_WLGP_GP_EVENTS = 1);
--
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_COHORT_LINKAGE_TABLE; 
