----------------------------------------------
--PROJECT: MELD-B 1377
--WP02 (Work Package 02) - Stage 01 
--AUTHOR: roberta.chiovoloni@swansea.ac.uk
--------------------------------------------------------
--AIM: Extracting subset of health datasources for the ALF_PE of interest (i.e. included in SMC cohort). WP02_COHORT_TABLE is the table for the SMC cohort

--Note: Given the amount of health record we suggest to turn off the auto-commit and to use to manual commit 
----------------------------------------------------------

--Drop table created-- run this if the tables are already available in the database 
--
--CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_WLGP_EVENTS_EXT');
--
--CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_PEDW_SPELL_EXT');
--CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_PEDW_EPI_EXT');
--CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_PEDW_DIAG_EXT');
--CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_PEDW_OPER_EXT');
--CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_PEDW_ADM_EXT');
--
--CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_OPDW_OUT_EXT');
--CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_OPDW_DIAG_EXT');
--CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_OPDW_OPER_EXT');
--
--CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_EDDS_EXT');
----------------------------------------------------------
----------
--WLGP EXTRACTION  - NOTE that for the WLGP we reduce the number of columns in the table given the amount of data. 
-- The information can be recalled joining the WP02_WLGP_EVENTS_EXT table with the appropriate tables or views available in SAIL 
----------
CALL FNC.DROP_IF_EXISTS ('SAILW1377V.WP02_WLGP_EVENTS_EXT');

--Create table 
CREATE TABLE SAILW1377V.WP02_WLGP_EVENTS_EXT (
	ALF_PE BIGINT,
	ALF_STS_CD VARCHAR(2),
	GNDR_CD VARCHAR(1), 
	WOB DATE, 
	DOD DATE,
	PRAC_CD_PE BIGINT, 
	LOCAL_NUM_PE BIGINT, 
	EVENT_CD_VRS VARCHAR(1), 
	EVENT_CD VARCHAR(40), 
	EVENT_VAL DECIMAL(31,8), 
	EVENT_DT DATE,
	EPISODE VARCHAR(1)
	)
DISTRIBUTE BY HASH(ALF_PE, PRAC_CD_PE, LOCAL_NUM_PE); 
COMMIT; 
--
CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SAILW1377V.WP02_WLGP_EVENTS_EXT WITH DISTRIBUTION AND DETAILED INDEXES ALL');
COMMIT;
--
ALTER TABLE SAILW1377V.WP02_WLGP_EVENTS_EXT ACTIVATE NOT LOGGED INITIALLY;
-- 
--Insert into the table -> run this year by year and committ each time 

INSERT INTO SAILW1377V.WP02_WLGP_EVENTS_EXT
SELECT 
	A.ALF_PE, A.ALF_STS_CD, T1.GNDR_CD, T1.WOB, T1.DOD, A.PRAC_CD_PE, A.LOCAL_NUM_PE, 
	A.EVENT_CD_VRS, A.EVENT_CD, A.EVENT_VAL, A.EVENT_DT, 
	A.EPISODE
	FROM 
		SAIL1377V.WLGP_GP_EVENT_CLEANSED_20230401 A
	JOIN 
		SAILW1377V.WP02_COHORT_TABLE T1
	ON 
		A.ALF_PE = T1.ALF_PE
	WHERE 
		A.PRAC_CD_PE IS NOT NULL 
	AND
		--YEAR(A.EVENT_DT) <=2000 AND A.EVENT_DT >= '1990-01-01' 
		--(YEAR(A.EVENT_DT) = 2001 OR YEAR(A.EVENT_DT) = 2002)
		--(YEAR(A.EVENT_DT) = 2003 OR YEAR(A.EVENT_DT) = 2004) 
		--(YEAR(A.EVENT_DT) = 2005 OR YEAR(A.EVENT_DT) = 2006)
		--(YEAR(A.EVENT_DT) = 2007 OR YEAR(A.EVENT_DT) = 2008)
		--(YEAR(A.EVENT_DT) = 2009 OR YEAR(A.EVENT_DT) = 2010)
		--(YEAR(A.EVENT_DT) = 2011 OR YEAR(A.EVENT_DT) = 2012)
		--(YEAR(A.EVENT_DT) = 2013 OR YEAR(A.EVENT_DT) = 2014)
		--YEAR(A.EVENT_DT) = 2015
		--YEAR(A.EVENT_DT) = 2016
		--YEAR(A.EVENT_DT) = 2017
		--YEAR(A.EVENT_DT) = 2018
		--YEAR(A.EVENT_DT) = 2019
		--YEAR(A.EVENT_DT) = 2020
		--YEAR(A.EVENT_DT) = 2021
		YEAR(A.EVENT_DT) = 2022
; 
COMMIT; 

---------------------
--PEDW EXTRACTION - We create different extraction tables for teh different PEDW datasources 
---------------------
--
CREATE TABLE SAILW1377V.WP02_PEDW_SPELL_EXT LIKE SAIL1377V.PEDW_SPELL_20230605
DISTRIBUTE BY HASH(ALF_PE); 
COMMIT; 
--
CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SAILW1377V.WP02_PEDW_SPELL_EXT WITH DISTRIBUTION AND DETAILED INDEXES ALL');
COMMIT;
--
ALTER TABLE SAILW1377V.WP02_PEDW_SPELL_EXT ACTIVATE NOT LOGGED INITIALLY; 
COMMIT;
ALTER TABLE SAILW1377V.WP02_PEDW_SPELL_EXT ADD WOB DATE;
COMMIT;
--
INSERT INTO SAILW1377V.WP02_PEDW_SPELL_EXT 
	SELECT 
		A.*, B.WOB
	FROM 
		SAIL1377V.PEDW_SPELL_20230605 A
	JOIN 
		SAILW1377V.WP02_COHORT_TABLE B 
	ON 
		A.ALF_PE = B.ALF_PE 
	WHERE 
		--ALF_PE IN (SELECT ALF_PE FROM SAILW1377V.WP02_COHORT_TABLE)
	--AND 
		ADMIS_DT >= '1990-01-01' AND ADMIS_DT < SAILW1377V.COHORT_END_DT
	; 
COMMIT;
--
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_PEDW_SPELL_EXT ;
--
--

CREATE TABLE SAILW1377V.WP02_PEDW_ADM_EXT LIKE SAIL1377V.PEDW_ADMISSIONS_20230605
DISTRIBUTE BY HASH(ALF_PE); 
COMMIT; 
--
CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SAILW1377V.WP02_PEDW_ADM_EXT WITH DISTRIBUTION AND DETAILED INDEXES ALL');
COMMIT;
--
ALTER TABLE SAILW1377V.WP02_PEDW_ADM_EXT ACTIVATE NOT LOGGED INITIALLY; 
COMMIT;
ALTER TABLE SAILW1377V.WP02_PEDW_ADM_EXT ADD WOB DATE;
COMMIT;
--
INSERT INTO SAILW1377V.WP02_PEDW_ADM_EXT
	SELECT 
		A.*, B.WOB
	FROM 
		SAIL1377V.PEDW_ADMISSIONS_20230605 A
	JOIN 
		SAILW1377V.WP02_COHORT_TABLE B 
	ON 
		A.ALF_PE = B.ALF_PE 
	WHERE 
		END_DATE >= '1990-01-01' AND END_DATE < SAILW1377V.COHORT_END_DT
	; 
COMMIT;
--
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_PEDW_ADM_EXT ;

--
--
CREATE TABLE SAILW1377V.WP02_PEDW_EPI_EXT LIKE SAIL1377V.PEDW_EPISODE_20230605; 
--
CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SAILW1377V.WP02_PEDW_EPI_EXT WITH DISTRIBUTION AND DETAILED INDEXES ALL');
COMMIT;
--
ALTER TABLE SAILW1377V.WP02_PEDW_EPI_EXT ACTIVATE NOT LOGGED INITIALLY; 
COMMIT;
ALTER TABLE SAILW1377V.WP02_PEDW_EPI_EXT ADD ALF_PE BIGINT; 
COMMIT; 
ALTER TABLE SAILW1377V.WP02_PEDW_EPI_EXT ADD WOB DATE;
COMMIT;

--Insert in chunks 
INSERT INTO SAILW1377V.WP02_PEDW_EPI_EXT
	SELECT 
		A.*, B.ALF_PE AS ALF_PE, B.WOB
	FROM 
		SAIL1377V.PEDW_EPISODE_20230605 A 
	JOIN 
		SAILW1377V.WP02_PEDW_SPELL_EXT B 
	ON 
		A.PROV_UNIT_CD = B.PROV_UNIT_CD
	AND 
		A.SPELL_NUM_PE = B.SPELL_NUM_PE
	WHERE
		--A.EPI_STR_DT >= '1990-01-01' AND A.EPI_STR_DT < '2010-01-01'
		--A.EPI_STR_DT >= '2010-01-01' AND A.EPI_STR_DT < '2015-01-01'
		--A.EPI_STR_DT >= '2015-01-01' AND A.EPI_STR_DT < '2017-01-01'
		--A.EPI_STR_DT >= '2017-01-01' AND A.EPI_STR_DT < '2019-01-01'
		A.EPI_STR_DT >= '2019-01-01' AND A.EPI_STR_DT < SAILW1377V.COHORT_END_DT
	; 
COMMIT;
--
--
CREATE TABLE SAILW1377V.WP02_PEDW_DIAG_EXT LIKE SAIL1377V.PEDW_DIAG_20230605; 
COMMIT; 
--
CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SAILW1377V.WP02_PEDW_DIAG_EXT WITH DISTRIBUTION AND DETAILED INDEXES ALL');
COMMIT;
--
ALTER TABLE SAILW1377V.WP02_PEDW_DIAG_EXT ACTIVATE NOT LOGGED INITIALLY; 
COMMIT;
ALTER TABLE SAILW1377V.WP02_PEDW_DIAG_EXT ADD ALF_PE BIGINT; 
COMMIT; 
ALTER TABLE SAILW1377V.WP02_PEDW_DIAG_EXT ADD WOB DATE;
COMMIT;
--
INSERT INTO SAILW1377V.WP02_PEDW_DIAG_EXT
	SELECT 
		A.*, B.ALF_PE AS ALF_PE, B.WOB
	FROM 
		SAIL1377V.PEDW_DIAG_20230605 A 
	JOIN 
		SAILW1377V.WP02_PEDW_SPELL_EXT B 
	ON 
		A.PROV_UNIT_CD = B.PROV_UNIT_CD
	AND 
		A.SPELL_NUM_PE = B.SPELL_NUM_PE
	;
COMMIT;
--
--
CREATE TABLE SAILW1377V.WP02_PEDW_OPER_EXT LIKE SAIL1377V.PEDW_OPER_20230605; 
COMMIT;
--
CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SAILW1377V.WP02_PEDW_OPER_EXT WITH DISTRIBUTION AND DETAILED INDEXES ALL');
COMMIT;
--
ALTER TABLE SAILW1377V.WP02_PEDW_OPER_EXT ACTIVATE NOT LOGGED INITIALLY; 
COMMIT;
ALTER TABLE SAILW1377V.WP02_PEDW_OPER_EXT ADD ALF_PE BIGINT; 
COMMIT; 
ALTER TABLE SAILW1377V.WP02_PEDW_OPER_EXT ADD WOB DATE;
COMMIT;
--
--Insert in chunks 
INSERT INTO SAILW1377V.WP02_PEDW_OPER_EXT
	SELECT 
		A.*, B.ALF_PE AS ALF_PE, B.WOB
	FROM 
		SAIL1377V.PEDW_OPER_20230605 A
	JOIN 
		SAILW1377V.WP02_PEDW_SPELL_EXT B 
	ON 
		A.PROV_UNIT_CD = B.PROV_UNIT_CD
	AND 
		A.SPELL_NUM_PE = B.SPELL_NUM_PE
	WHERE 
		--A.OPER_DT >= '1990-01-01' AND A.OPER_DT < '2010-01-01'
		--A.OPER_DT >= '2010-01-01' AND A.OPER_DT < '2015-01-01'
		--A.OPER_DT >= '2015-01-01' AND A.OPER_DT < '2017-01-01'
		--A.OPER_DT >= '2017-01-01' AND A.OPER_DT < '2019-01-01'
		A.OPER_DT >= '2019-01-01' AND A.OPER_DT < SAILW1377V.COHORT_END_DT
	; 
COMMIT;
--
--Check(s)
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_PEDW_SPELL_EXT; 
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_PEDW_EPI_EXT;
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_OPDW_DIAG_EXT; 
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_OPDW_OPER_EXT; 

---------------
--EDDS DATASET 
---------------
CREATE TABLE SAILW1377V.WP02_EDDS_EXT LIKE SAIL1377V.EDDS_EDDS_20230601;
TRUNCATE TABLE SAILW1377V.WP02_EDDS_EXT IMMEDIATE; 
--
INSERT INTO SAILW1377V.WP02_EDDS_EXT
	WITH T1 AS (
		SELECT 
			A.*
		FROM 
			SAIL1377V.EDDS_EDDS_20230601 A
		WHERE 
			ALF_PE IN (SELECT ALF_PE FROM SAILW1377V.WP02_COHORT_TABLE)
	)
	SELECT * FROM T1;
--
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_EDDS_EXT;
--
----------------
--OPDW DATASOURCE - We create different extraction tables for teh different OPDW datasources 
---------------
--Create table for each OPDW dataset

CREATE TABLE SAILW1377V.WP02_OPDW_OUT_EXT LIKE SAIL1377V.OPDW_OUTPATIENTS_20230601
DISTRIBUTE BY HASH(ALF_PE); 
COMMIT; 
--
CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SAILW1377V.WP02_OPDW_OUT_EXT WITH DISTRIBUTION AND DETAILED INDEXES ALL');
COMMIT;
--
ALTER TABLE SAILW1377V.WP02_OPDW_OUT_EXT ACTIVATE NOT LOGGED INITIALLY;
--
CREATE TABLE SAILW1377V.WP02_OPDW_DIAG_EXT LIKE SAIL1377V.OPDW_OUTPATIENTS_DIAG_20230601; 
COMMIT; 
--
CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SAILW1377V.WP02_OPDW_DIAG_EXT WITH DISTRIBUTION AND DETAILED INDEXES ALL');
COMMIT;
--
ALTER TABLE SAILW1377V.WP02_OPDW_DIAG_EXT ACTIVATE NOT LOGGED INITIALLY;
--
CREATE TABLE SAILW1377V.WP02_OPDW_OPER_EXT LIKE SAIL1377V.OPDW_OUTPATIENTS_OPER_20230601; 
COMMIT;
--
CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE SAILW1377V.WP02_OPDW_OPER_EXT WITH DISTRIBUTION AND DETAILED INDEXES ALL');
COMMIT;
--
ALTER TABLE SAILW1377V.WP02_OPDW_OPER_EXT ACTIVATE NOT LOGGED INITIALLY;
--
INSERT INTO SAILW1377V.WP02_OPDW_OUT_EXT
	WITH t1 AS (
		SELECT 
			ALF_PE 
		FROM 
			SAILW1377V.WP02_COHORT_TABLE
	)
	SELECT 
		A.*
	FROM 
		SAIL1377V.OPDW_OUTPATIENTS_20230601 A
	JOIN 
		T1
	ON 
		A.ALF_PE = T1.ALF_PE
	WHERE REF_DT >= '1990-01-01' AND REF_DT <= SAILW1377V.COHORT_END_DT;
COMMIT; 
--
--Joining opdw diag with alf_pe on opwd_oupatients 
ALTER TABLE SAILW1377V.WP02_OPDW_DIAG_EXT 
ADD COLUMN ALF_PE BIGINT; 

INSERT INTO SAILW1377V.WP02_OPDW_DIAG_EXT
	WITH T1 AS (
		SELECT 
			A.*, B.ALF_PE AS ALF_PE 
		FROM 
			SAIL1377V.OPDW_OUTPATIENTS_DIAG_20230601 A
		JOIN 
			SAIL1377V.OPDW_OUTPATIENTS_20230601 B
		ON 
			A.PROV_UNIT_CD = B.PROV_UNIT_CD 
			AND A.CASE_REC_NUM_PE = B.CASE_REC_NUM_PE 
			AND A.ATTEND_DT = B.ATTEND_DT 
			AND A.ATT_ID_PE = B.ATT_ID_PE 
	)
	SELECT * 
	FROM 
		T1
	WHERE 
		ALF_PE IN (SELECT ALF_PE FROM SAILW1377V.WP02_COHORT_TABLE) 
	AND
		ATTEND_DT >= '1990-01-01' AND ATTEND_DT <= SAILW1377V.COHORT_END_DT;
COMMIT; 
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_OPDW_DIAG_EXT; 
--
--joining WP02_OPDW_OPER_EXT with opwd_oupatients to add ALF_PE
ALTER TABLE SAILW1377V.WP02_OPDW_OPER_EXT
ADD COLUMN ALF_PE BIGINT;
--
INSERT INTO SAILW1377V.WP02_OPDW_OPER_EXT
	WITH T1 AS (
		SELECT 
			A.*, B.ALF_PE AS ALF_PE
		FROM 
			SAIL1377V.OPDW_OUTPATIENTS_OPER_20230601 A
		JOIN 
			SAIL1377V.OPDW_OUTPATIENTS_20230601 B
		ON 
			A.PROV_UNIT_CD = B.PROV_UNIT_CD 
			AND A.CASE_REC_NUM_PE = B.CASE_REC_NUM_PE 
			AND A.ATTEND_DT = B.ATTEND_DT 
			AND A.ATT_ID_PE = B.ATT_ID_PE 
	)
	SELECT * 
	FROM 
		t1
	WHERE 
		ALF_PE IN (SELECT ALF_PE FROM SAILW1377V.WP02_COHORT_TABLE ) 
	AND 
		ATTEND_DT >= '1990-01-01' AND ATTEND_DT <= SAILW1377V.COHORT_END_DT;
COMMIT; 
--
--Check(s)
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_OPDW_OUT_EXT; 
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_OPDW_DIAG_EXT;
SELECT COUNT(DISTINCT ALF_PE) FROM SAILW1377V.WP02_OPDW_OPER_EXT; 
--
